### ISSUE TITLE
Strange filtering behaviour 

### ISSUE THREAD

**Issue by yanischauvel** [YMC-22/smart-filter#42]
Hi, I need to display, filtering and search in all post (all categories, tags and custom taxonomy) at the first opening (Taxonomy Relation
Select taxonomy relation: OR)  and then be able to filter with Taxonomy Relation
Select taxonomy relation: AND. 

I mean for now, if I choose OR in query options, when I select a taxonomy or tag, there are more results.  If I select AND in, Query options, I have no results.

The behaviour that I need is:

Display All posts at the first opening and then use filters to restrict the results. 

Is it possible? 

Thanks for answer

**Comment by YMC-22** [comment]
Hi!
You can use the post filter to solve your tasks. The filter has fine-tuning with many options. The Relation parameter is responsible for the logic of selecting posts. If the OR parameter is selected, the number of filtered posts will be greater, otherwise it will be less. The operation of the filter itself is based on the operation of the global object WP Query of the WordPress core. Study the documentation on using this functionality in more detail.
https://developer.wordpress.org/reference/classes/wp_query/
